version: '3'

networks:
    cicd:
        driver: bridge

services:
    jenkins: 
        build: ./jenkins-master
        image: cicd/jenkins-master:1.0.0
        container_name: cicd-jenkins-master
        ports:
         - "8080:8080"
         - "443:443"
         - "5000:5000"
        networks:
         - cicd
        environment:
         - JAVA_OPTS="-Xmx2g"
        volumes:
         - jenkins-data:/var/jenkins_home
         - /var/run/docker.sock:/var/run/docker.sock
    
    sonar:
        build: ./sonar
        image: cicd/sonar:1.0.0
        container_name: cicd-sonar
        ports:
         - "9000:9000"
        volumes:
         - sonar_conf:/opt/sonarqube/conf
         - sonar_data:/opt/sonarqube/data
         - sonar_ext:/opt/sonarqube/extensions
         - sonar_bundle:/opt/sonarqube/lib/bundled-plugins
        networks: 
         - cicd
        depends_on:
         - sonar-db
        environment:
         - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
         - SONARQUBE_JDBC_USERNAME=sonar
         - SONARQUBE_JDBC_PASSWORD=sonar
    
    sonar-db:
        restart: always
        build: ./sonar-db
        image: cicd/postgres:1.0.0
        container_name: cicd-postgres
        environment:
         - POSTGRES_USER=sonar
         - POSTGRES_PASSWORD=sonar
        volumes:
         - /opt/postgres/data:/var/lib/postgresql/data
        networks:
         - cicd

volumes:
    jenkins-data:
    sonar_conf:
    sonar_data:
    sonar_ext:
    sonar_bundle: